version: '3.8'
services:
  api:
    container_name: todo-app-instance
    build: .
    environment:
      PORT: 3000
      DB_URL: "mongodb://mongodb:27017/test2"
    ports:
      - "3000:3000"

  mongodb:
    container_name: mongodb-server
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - "mongo-data:/data/db"
volumes:
  mongo-data: